export const packageName = '@multivisio/nswow';

export const baseComponentsToInstall = [
  'Container/aside-content-container',
  'Container/columns-container',
  'CV/cv',
  'CV/cv-time-span',
  'Lists/alphanumeric-list',
  'Lists/list-item',
  'Lists/ordered-list',
  'Lists/unordered-list',
  'Media/image',
  'Media/interactive-element',
  'Media/table',
  'Media/video',
  'Misc/anchor',
  'PDF/pdf-chapter-title',
  'PDF/pdf-cover',
  'PDF/pdf-pagebreak',
  'PDF/pdf-publication-title',
  'PDF/pdf-toc-item',
  'PDF/pdf-toc-item-blank',
  'PDF/pdf-toc-item-title',
  'PDF/pdf-toc-page',
  'Properties/alignment',
  'Properties/hide-quote-characters',
  'Properties/pdf-spacer',
  'Properties/width',
  'Signatures/signature-container',
  'Signatures/signature-item',
  'Text/footnote-container',
  'Text/footnote-item',
  'Text/lead',
  'Text/paragraph',
  'Text/quote',
  'Text/quote-with-portrait',
  'Titles/title-h1',
  'Titles/title-h2',
  'Titles/title-h3',
  'Titles/title-h4',
  'Titles/title-h5',
  'Titles/title-h6',
];

export default {
  packageName,
  baseComponentsToInstall,
};
